#!/bin/sh

# Pre-install script for dartos-plymouth-theme 1.0+ . Removes old version of official dartos-plymouth-theme package and install new version of it.

set -e

echo "Looking for old versions of dartos-plymouth-theme"

if [ -f "/usr/share/plymouth/themes/dartos-plymouth-theme" ]; then
        rm -f /usr/share/plymouth/themes/dartos-plymouth-theme
        echo "Removed old dartos-plymouth-theme from system"
fi

exit 0
